defmodule Feriendaten.Repo.Migrations.AddUniqueName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:levels, [:name], name: "levels_unique_name_index")

    create unique_index(:levels, [:slug], name: "levels_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:levels, [:slug], name: "levels_unique_slug_index")

    drop_if_exists unique_index(:levels, [:name], name: "levels_unique_name_index")
  end
end
