defmodule Feriendaten.Repo.Migrations.AddTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:levels) do
      modify :position, :bigint, null: false
      modify :name, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:levels) do
      remove :updated_at
      remove :inserted_at
      modify :name, :text, null: true
      modify :position, :bigint, null: true
    end
  end
end