defmodule Feriendaten.Repo.Migrations.AddLegacyLocationResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:legacy_locations, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :legacy_id, :bigint, null: false
      add :legacy_name, :text, null: false
      add :legacy_slug, :text, null: false
      add :legacy_parent_id, :bigint

      add :location_id,
          references(:locations,
            column: :id,
            name: "legacy_locations_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:legacy_locations, "legacy_locations_location_id_fkey")

    drop table(:legacy_locations)
  end
end
