defmodule Feriendaten.Repo.Migrations.AddLocationResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :code, :text
      add :slug, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :level_id,
          references(:levels,
            column: :id,
            name: "locations_level_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:locations, [:slug], name: "locations_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:locations, [:slug], name: "locations_unique_slug_index")

    drop constraint(:locations, "locations_level_id_fkey")

    drop table(:locations)
  end
end